### ISSUE TITLE
Add quickstart dev documentations

### ISSUE THREAD

**Issue by GDreyV** [vrntrans/vrnbus#2]
Возможно стоит написать пару слов про то, как быстро развернуть проект, например:
1. Install python 3 with pip
2. run pip install -r requirements.txt
3. unzip test_data.7z (7z? really?) to test_data folder.
4. run python main.py and open browser at localhost:8080.
Что делать с чатботом? Надо либо его отключать, если нет параметров, либо написать, где получить параметры.

**Comment by xeningem** [comment]
> unzip test_data.7z (7z? really?) to test_data folder.
7z есть на всех платформах, а tar.gz мне не хотелось, но могу и tar.gz сделать, но он будет в 30 раз больше.

**Comment by GDreyV** [comment]
А просто zip чем плох? Он также есть на всех платформах, но на современных версиях ещё есть нативная поддержка

**Comment by xeningem** [comment]
Мне не хочется делать репозиторий в 30 раз больше только из-за нативной поддержки zip.  С другой стороны я могу положить рядом zip архив с 5 файлами, вместо 500, но это тоже странно. Предлагаю отложить обсуждение формата архива на потом.

**Comment by xeningem** [comment]
Fixed
