### ISSUE TITLE
Орфографическая ошибка в описании поля

### ISSUE THREAD

**Issue by evgkis79** [vrntrans/vrnbus#5]
На странице "Прибытие" - орфографическая ошибка в описании поля ввода в слове "маршрутов", см.    
 https://prnt.sc/iwj8l2

**Comment by xeningem** [comment]
Поправил
![image](https://user-images.githubusercontent.com/4473055/37978544-f7a14d50-31ee-11e8-8ce2-8185329d20d9.png)
