### ISSUE TITLE
Название ниспадающего списка «Маршруты» может быть добавлено в строку ввода маршрутов

### ISSUE THREAD

**Issue by TkachevAlexander** [vrntrans/vrnbus#9]
1. Открыть страницу "Прибытие" / "Автобусы" / "Карта"
2. Выбрать из ниспадающего списка любой номер маршрута
3. Выбрать название ниспадающего списка «Маршруты»

Ожидаемый результат:
Название ниспадающего списка «Маршруты» - нельзя выбрать.

Фактический результат:
Название ниспадающего списка «Маршруты»  - добавляется в строку ввода.
![5](https://user-images.githubusercontent.com/40641014/42105253-5d4c13fa-7bd8-11e8-9531-341716e57520.jpg)

**Comment by xeningem** [comment]
Fixed
